baseurl = "/"
title = "Digital Notebook of @linuscodes"

summaryLength = 25

[Params]
   mainSections = ["post"]
   intro = true
   headline = "Digital Notebook of @linuscodes"
   description = "This is my digital Notebook aka blog to frequently share some thoughts on the internet."
   github = "https://github.com/linuscodes"
   twitter = "https://twitter.com/linuscodes"
   instagram = "https://instagram.com/linuscodes"
   email = "moin@linuscodes.com"
   opengraph = true
   dateFormat = "Monday, January 2, 2006"

[Permalinks]
   post = "/:year/:month/:day/:filename/"
